In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings as warnings

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df_sub = pd.read_csv('sample_submission.csv')

In [3]:
df_train

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,27500
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,30000
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes,86900
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,Black,None reported,NaN,84900
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,28995

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [5]:
df_test

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes
1,188534,Land,Rover Defender SE,2020,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes
2,188535,Ford,Expedition Limited,2022,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,Ebony,None reported,NaN
3,188536,Audi,A6 2.0T Sport,2016,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,Black,None reported,NaN
4,188537,Audi,A6 2.0T Premium Plus,2018,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
125685,314218,Mercedes-Benz,GL-Class GL 450 4MATIC,2014,83315,Gasoline,362.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Black,None reported,Yes
125686,314219,Audi,Q7 55 Prestige,2019,29336,Gasoline,3.0 Liter Turbo,Automatic,White,Black,None reported,NaN
125687,314220,Audi,A6 3.0T Premium Plus,2012,77634,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes
125688,314221,Audi,Q7 3.0T Premium,2012,112000,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes
125689,314222,Chevrolet,Tahoe LT,2018,66840,Gasoline,355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,None reported,Yes

In [6]:
df_train.shape

(188533, 13)

In [7]:
df_train.isna().sum()[df_train.isna().sum() != 0]

fuel_type       5083
accident        2452
clean_title    21419
dtype: int64

In [8]:
df_train['fuel_type'].sort_values()

47286     Diesel
161330    Diesel
161291    Diesel
161287    Diesel
27336     Diesel
           ...
188368       NaN
188455       NaN
188462       NaN
188484       NaN
188489       NaN
Name: fuel_type, Length: 188533, dtype: object

In [9]:
df_train['fuel_type'] = df_train['fuel_type'].fillna(np.random.choice(df_train['fuel_type'].dropna().values))
df_test['fuel_type'] = df_test['fuel_type'].fillna(np.random.choice(df_test['fuel_type'].dropna().values))

In [10]:
df_train['accident'].sort_values()

106155    At least 1 accident or damage reported
73100     At least 1 accident or damage reported
31254     At least 1 accident or damage reported
164235    At least 1 accident or damage reported
54786     At least 1 accident or damage reported
                           ...
187885                                       NaN
188140                                       NaN
188425                                       NaN
188505                                       NaN
188507                                       NaN
Name: accident, Length: 188533, dtype: object

In [11]:
df_train['clean_title'].sort_values()

0         Yes
125656    Yes
125657    Yes
125658    Yes
125659    Yes
         ...
188507    NaN
188511    NaN
188513    NaN
188520    NaN
188531    NaN
Name: clean_title, Length: 188533, dtype: object

In [12]:
df_train['accident'] = df_train['accident'].fillna(np.random.choice(df_train['accident'].dropna().values))
df_test['accident'] = df_test['accident'].fillna(np.random.choice(df_test['accident'].dropna().values))

In [13]:
df_train['clean_title'] = df_train['clean_title'].fillna(np.random.choice(df_train['clean_title'].dropna().values))
df_test['clean_title'] = df_test['clean_title'].fillna(np.random.choice(df_test['clean_title'].dropna().values))

In [14]:
df_train = df_train.drop('id' , axis=1)
df_test = df_test.drop('id' , axis=1)

In [15]:
df_train = df_train.drop('model' , axis=1)
df_test = df_test.drop('model' , axis=1)

In [16]:
df_test['engine'] = df_test['engine'].replace(to_replace='177.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas', value='139.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas')

In [17]:
set(df_test['brand'].unique()).difference(set(df_train['brand'].unique()))

set()

In [18]:
set(df_test['engine'].unique()).difference(set(df_train['engine'].unique()))

set()

In [19]:
set(df_test['transmission'].unique()).difference(set(df_train['transmission'].unique()))

set()

In [20]:
set(df_test['ext_col'].unique()).difference(set(df_train['ext_col'].unique()))

set()

In [21]:
set(df_test['int_col'].unique()).difference(set(df_train['int_col'].unique()))

set()

In [22]:
set(df_test['accident'].unique()).difference(set(df_train['accident'].unique()))

set()

In [23]:
set(df_test['clean_title'].unique()).difference(set(df_train['clean_title'].unique()))

set()

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
label = LabelEncoder()

In [26]:
df_train['brand'] = label.fit_transform(df_train['brand'])
df_test['brand'] = label.transform(df_test['brand'])

In [27]:
df_train['fuel_type'] = label.fit_transform(df_train['fuel_type'])
df_test['fuel_type'] = label.transform(df_test['fuel_type'])

In [28]:
df_train['engine'] = label.fit_transform(df_train['engine'])
df_test['engine'] = label.transform(df_test['engine'])

In [29]:
df_train['transmission'] = label.fit_transform(df_train['transmission'])
df_test['transmission'] = label.transform(df_test['transmission'])

In [30]:
df_train['ext_col'] = label.fit_transform(df_train['ext_col'])
df_test['ext_col'] = label.transform(df_test['ext_col'])

In [31]:
df_train['int_col'] = label.fit_transform(df_train['int_col'])
df_test['int_col'] = label.transform(df_test['int_col'])

In [32]:
df_train['accident'] = label.fit_transform(df_train['accident'])
df_test['accident'] = label.transform(df_test['accident'])

In [33]:
df_train['clean_title'] = label.fit_transform(df_train['clean_title'])
df_test['clean_title'] = label.transform(df_test['clean_title'])

In [34]:
df_train.corr()['price']

brand           0.017657
model_year      0.231795
milage         -0.283067
fuel_type       0.015427
engine          0.208285
transmission    0.014560
ext_col        -0.017342
int_col         0.035174
accident        0.125122
clean_title          NaN
price           1.000000
Name: price, dtype: float64

In [35]:
X_train = df_train.drop('price', axis=1)
y_train = df_train['price']
X_test = df_test.copy()

In [36]:
df_train.shape

(188533, 11)

In [38]:
from keras import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [39]:
model = Sequential()

In [40]:
model.add(Dense(units=26, activation='relu',  use_bias=False , input_shape=(10, )))
model.add(Dense(units=13, activation='relu', use_bias=False))
model.add(Dense(units=1, activation='linear'))

/home/msi/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-01-12 21:48:20.396146: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [41]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss = 'binary_crossentropy', metrics = ['accuracy'])

In [42]:
y_train

0          4200
1          4999
2         13900
3         45000
4         97500
          ...
188528    27500
188529    30000
188530    86900
188531    84900
188532    28995
Name: price, Length: 188533, dtype: int64

In [44]:
model.fit(X_train , y_train, epochs= 20)

Epoch 1/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 5s 734us/step - accuracy: 0.0000e+00 - loss: 707231.0625
Epoch 2/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 4s 734us/step - accuracy: 0.0000e+00 - loss: 707230.5625
Epoch 3/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 4s 722us/step - accuracy: 0.0000e+00 - loss: 707229.6875
Epoch 4/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 5s 765us/step - accuracy: 0.0000e+00 - loss: 707229.6250
Epoch 5/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 4s 730us/step - accuracy: 0.0000e+00 - loss: 707231.0000
Epoch 6/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 5s 920us/step - accuracy: 0.0000e+00 - loss: 707230.6875
Epoch 7/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 5s 922us/step - accuracy: 0.0000e+00 - loss: 707230.9375
Epoch 8/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 5s 888us/step - accuracy: 0.0000e+00 - loss: 707229.6875
Epoch 9/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.0000e+00 - loss: 707229.5625
Epoch 10/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 5s 786us/step - accuracy: 0.0000e+00 - loss: 707229.8750
Epoch 11/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.0000e+00 - loss: 707228.8125
Epoch 12/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.0000e+00 - loss: 707231.0000
Epoch 13/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 4s 711us/step - accuracy: 0.0000e+00 - loss: 707229.2500
Epoch 14/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.0000e+00 - loss: 707230.4375
Epoch 15/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 6s 933us/step - accuracy: 0.0000e+00 - loss: 707229.2500
Epoch 16/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 5s 846us/step - accuracy: 0.0000e+00 - loss: 707230.8125
Epoch 17/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.0000e+00 - loss: 707229.5000
Epoch 18/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 5s 909us/step - accuracy: 0.0000e+00 - loss: 707229.9375
Epoch 19/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 4s 740us/step - accuracy: 0.0000e+00 - loss: 707229.4375
Epoch 20/20
5892/5892 ━━━━━━━━━━━━━━━━━━━━ 4s 634us/step - accuracy: 0.0000e+00 - loss: 707230.0000

In [45]:
y_pred = model.predict(X_test)

3928/3928 ━━━━━━━━━━━━━━━━━━━━ 1s 290us/step

In [46]:
df_sub['price'] = y_pred

In [47]:
df_sub.to_csv('sub_NN.csv', index=False, index_label=False)